name: one-health

services:
  db:
    image: postgres
    restart: always
    env_file:
      - .env
    networks:
      - one-health
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data  
  api: 
    build: 
      context: ./server
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: ./server/.env
    volumes:
      - ./server:/app
      - /app/node_modules
    networks:
      - one-health
    ports:
      - 3000:4004
    depends_on:
      - db
  client:
    build: 
      context: ./client
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./client:/app
      - /app/node_modules
    networks:
      - one-health
    ports:
      - 5173:5173
    depends_on:
      - api

volumes:
  pgdata:
networks:
  one-health:
    driver: bridge
    
    