###
GET http://localhost:3000/setup

###

### 
POST http://localhost:3000
Content-Type: application/json

{
    "name": "Joel",
    "location": "Gilroy"
}

###

###
GET http://localhost:3000
###

GET http://localhost:3000/3

###
